services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - devnet
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - devnet
  minio:
    image: minio/minio:latest
    container_name: dev-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpass
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - devnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 10s
      retries: 5

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 minioadmin minioadminpass &&
        mc mb -p local/dev-bucket || echo 'Bucket already exists'
      "
    networks:
      - devnet
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql://devuser:devpass@postgres:5432/devdb
      S3_ENDPOINT: http://minio:9000
      REDIS_URL: redis://redis:6379
    depends_on:
      - minio
      - minio-init
      - postgres
      - redis
    networks:
      - devnet
    profiles:
      - production

volumes:
  postgres-data:
  minio-data:

networks:
  devnet:
