name: CI

on:
  push:
    branches: [main, test/github-actions]
  pull_request:
    branches: [main, test/github-actions]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4

      - name: Set up Bun runtime
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile

      - name: Generate Drizzle types
        run: bunx drizzle-kit generate

      - name: Lint TypeScript
        run: bun run lint

      - name: Run unit tests
        run: bun test

      - name: Build for production
        run: make build
